### ISSUE TITLE
04_05_full_main.py - nome da variável out_file não foi declarada na função download

### ISSUE THREAD

**Issue by medeirosthiago** [felipecruz/exemplos#1]
opa felipe, vi que na linha [26](https://github.com/felipecruz/exemplos/blob/master/04_05_full_main.py#L26) a variável _out_file_ não é referenciada nessa função, o parâmetro passado é o _output_.

Apesar que dos dois jeitos funcionam..

``` python
def download(response, output):
    total_downloaded = 0
    while True:
        data = response.read(BUFF_SIZE)
        total_downloaded += len(data)
        if not data:
            break
        output.write(data)
        print('Downloaded {bytes}'.format(bytes=total_downloaded))
```

**Comment by felipecruz** [comment]
Obrigado Thiago. Corrigi e testei fazendo um download :)

**Comment by medeirosthiago** [comment]
Fechado no commit 2e07e2d5510b0245409dd9e06f9c3a3816bc1241

**Comment by felipecruz** [comment]
Obrigado @medeirosthiiago

**Comment by medeirosthiago** [comment]
que isso @felipecruz , desculpe a demora! :)
