### ISSUE TITLE
erro ao executar exercicio 03_02_input.py 

### ISSUE THREAD

**Issue by asfelix** [felipecruz/exemplos#2]
Olá @felipecruz 

Adquiri recentemente o livro "Python - Escreva seus primeiros programas", e ao fazer o exemplo 03_02_input.py, obtive um erro ao executá-lo; enquanto que no livro o exemplo está como abaixo:

``` python
salario = int(input('Salario? '))
imposto = input('Imposto em % (ex.: 27.5)? ')
if imposto == '':
    imposto = 27.5
else:
    imposto = float(imposto)

print("Valor real: {0}".format(salario - (salario * (imposto * 0.01))))
```

enquanto que o exemplo aqui no github está:

``` python
salario = int(input('Salario? '))
imposto = input('Imposto em % (ex: 27.5)? ')
if not imposto:
    imposto = 27.5
else:
    imposto = float(imposto)
print("Valor real: {0}".format(salario - (salario * (imposto * 0.01))))
```

na execução de ambos os códigos recebo a seguinte mensagem de erro ao efetuar o teste sem o valor do imposto:

<pre>Traceback (most recent call last):
  File "03_02_input.py", line 2, in <module>
    imposto = input('Imposto em % (ex: 27.5)? ')
  File "<string>", line 0
    
    ^
SyntaxError: unexpected EOF while parsing
</pre>

Procurando pela mensagem de erro, acabei descobrindo que para corrigir este erro, deveria ter usado um raw_input ao invés do input na linha 2 onde é declarada a variável "imposto"; então meu código ficou desta forma para ser executado sem erros:

``` python
salario = int(input('Salario? '))
imposto = raw_input('Imposto em % (ex.: 27.5)? ')
if not imposto:
    imposto = 27.5
else:
    imposto = float(imposto)

print("Valor real: {0}".format(salario - (salario * (imposto * 0.01))))
```

Seria interessante uma explicação sobre as diferenças e quando usar o "input" ou o "raw"input"

**Comment by asfelix** [comment]
Ops..., nem havia percebido que eu estava com a versão 2.x do Python em minha máquina, pesquisando um pouco mais encontrei a documentação explicando que o raw_input do python 2 foi renomeado para input no python 3: https://www.python.org/dev/peps/pep-3111/

**Comment by felipecruz** [comment]
Fala! Essa mudança já causou muita confusão :) posso fechar então?

**Comment by asfelix** [comment]
Sim, pode fechar @felipecruz confusão desfeita. Muito obrigado.

Ps.: Parabéns pelo livro, estou ainda no inicio mas está ajudando muito.
Ps².: Não existe mais a lista de discussão do livro?

**Comment by felipecruz** [comment]
Fala @asfelix . Existe, mas até hoje não entrou ninguém. O pessoal da casa do código criou um fórum que eu, particularmente, acho bem melhor pra se comunicar: http://forum.casadocodigo.com.br/
